[profile.local]
eth-rpc-url = 'http://localhost:8545'

[profile.default]
src = "src"
out = "out"
libs = ["lib/forge-std", "lib/openzeppelin-contracts-upgradeable", "lib/forte-rules-engine"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forte-rules-engine/=lib/forte-rules-engine/src",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
